#!/usr/bin/env python3
# -*- coding: UTF-8 -*-
#
# generated by wxGlade 1.1.1 on Fri Sep 12 18:05:19 2025
#

# This is an automatically generated file.
# Manual changes will be overwritten without warning!

import wx
from wxasync import WxAsyncApp
import asyncio
from MyFrame import MyFrame


class GitCommander(WxAsyncApp):
    frame: MyFrame

    def OnInit(self):
        self.frame = MyFrame(None, wx.ID_ANY, "")
        self.SetTopWindow(self.frame)
        self.frame.Show()
        return True


# end of class GitCommander

if __name__ == "__main__":
    app = GitCommander(0)
    app.MainLoop()
