# -*- coding: UTF-8 -*-
#
# generated by wxGlade 1.1.1 on Sat May  2 06:45:44 2026
#
from typing import Literal, TYPE_CHECKING

import wx

from .Threader import Threader
# begin wxGlade: extracode
from . import constants as const
# end wxGlade


# end wxGlade


class CloneDialog(wx.Dialog):
    def __init__(self, *args, **kwds):
        # begin wxGlade: CloneDialog.__init__
        kwds["style"] = kwds.get("style", 0) | wx.DEFAULT_DIALOG_STYLE | wx.RESIZE_BORDER | wx.STAY_ON_TOP
        wx.Dialog.__init__(self, *args, **kwds)
        self.SetTitle("Clone Dialog")

        top_vert_sizer = wx.BoxSizer(wx.VERTICAL)

        self.gh_list = wx.ListCtrl(self, wx.ID_ANY, style=wx.BORDER_DEFAULT | wx.LC_HRULES | wx.LC_REPORT | wx.LC_SINGLE_SEL | wx.LC_SORT_ASCENDING | wx.LC_VRULES)
        self.gh_list.AppendColumn("Repo Name", format=wx.LIST_FORMAT_LEFT, width=181)
        self.gh_list.AppendColumn("Repo Description", format=wx.LIST_FORMAT_LEFT, width=181)
        top_vert_sizer.Add(self.gh_list, 1, wx.EXPAND, 0)

        sizer_alt_repo_entry = wx.BoxSizer(wx.HORIZONTAL)
        top_vert_sizer.Add(sizer_alt_repo_entry, 0, wx.EXPAND, 0)

        url_prompt = wx.StaticText(self, wx.ID_ANY, "or enter url:")
        sizer_alt_repo_entry.Add(url_prompt, 1, wx.EXPAND, 0)

        self.text_ctrl_url = wx.TextCtrl(self, wx.ID_ANY, "")
        sizer_alt_repo_entry.Add(self.text_ctrl_url, 9, wx.EXPAND, 0)

        sizer_repo_select_copy = wx.BoxSizer(wx.HORIZONTAL)
        top_vert_sizer.Add(sizer_repo_select_copy, 0, wx.EXPAND | wx.FIXED_MINSIZE, 0)

        self.btn_select_dest = wx.Button(self, wx.ID_ANY, "const.REPOS_DIRECTORY")
        self.btn_select_dest.SetLabel(const.REPOS_DIRECTORY)
        sizer_repo_select_copy.Add(self.btn_select_dest, 1, wx.EXPAND, 0)

        sizer_dlg_buttons = wx.StdDialogButtonSizer()
        top_vert_sizer.Add(sizer_dlg_buttons, 0, wx.ALIGN_RIGHT, 0)

        self.btn_clone = wx.Button(self, wx.ID_OK, "Clone!")
        self.btn_clone.Enable(False)
        self.btn_clone.SetDefault()
        sizer_dlg_buttons.AddButton(self.btn_clone)

        self.btn_cancel = wx.Button(self, wx.ID_CANCEL, "")
        sizer_dlg_buttons.AddButton(self.btn_cancel)

        sizer_dlg_buttons.Realize()

        self.SetSizer(top_vert_sizer)
        top_vert_sizer.Fit(self)
        top_vert_sizer.SetSizeHints(self)

        self.SetAffirmativeId(self.btn_clone.GetId())
        self.SetEscapeId(self.btn_cancel.GetId())

        self.Layout()
        self.init_gh_list()

        self.gh_list.Bind(wx.EVT_LIST_ITEM_DESELECTED, self.on_item_deselected)
        self.gh_list.Bind(wx.EVT_LIST_ITEM_SELECTED, self.on_item_selected)
        self.text_ctrl_url.Bind(wx.EVT_TEXT, self.on_text_changed)
        self.btn_select_dest.Bind(wx.EVT_BUTTON, self.select_repos_directory)
        # end wxGlade

    @property
    def url_type(self) -> Literal["GH", "URL"]:
        return "GH" if self.gh_list.GetSelectedItemCount() > 0 else "URL"

    @property
    def url(self) -> str:
        if self.gh_list.GetSelectedItemCount() > 0:
            selected =  self.gh_list.GetFirstSelected()
            name = self.gh_list.GetItem(selected, 0)
            return name.GetText()
        else:
            return self.text_ctrl_url.GetValue()

    @property
    def target_directory(self) -> str:
        return self.btn_select_dest.GetLabel()

    def init_gh_list(self):
        parent = self.Parent
        if hasattr(parent, 'threader') and isinstance(parent.threader, Threader):
            repos = parent.threader.get_gh_repos()
            for repo in repos:
                self.gh_list.Append(repo)
        pass

    def select_repos_directory(self, event: wx.CommandEvent):  # wxGlade: CloneDialog.<event_handler>
        with wx.DirDialog(self, "Choose a directory for your repo") as dlg:
            if dlg.ShowModal() == wx.ID_OK:
                # Get the selected directory path
                selected_dir = dlg.GetPath()
                self.btn_select_dest.SetLabel(selected_dir)
        event.Skip()

    def on_item_deselected(self, event):  # wxGlade: CloneDialog.<event_handler>
        if self.text_ctrl_url.GetValue() == '':
            self.btn_clone.Disable()
        event.Skip()

    def on_item_selected(self, event):  # wxGlade: CloneDialog.<event_handler>
        self.btn_clone.Enable()
        event.Skip()

    def on_text_changed(self, event):  # wxGlade: CloneDialog.<event_handler>
        if self.text_ctrl_url.GetValue() == "" and self.gh_list.GetSelectedItemCount() == 0: self.btn_clone.Disable()
        else: self.btn_clone.Enable()
        event.Skip()
# end of class CloneDialog
