# -*- coding: UTF-8 -*-
#
# generated by wxGlade 1.1.1 on Sat May  2 06:45:44 2026
#

import wx

# begin wxGlade: dependencies
# end wxGlade

# begin wxGlade: extracode
from . import constants as const
# end wxGlade


class CloneDialog(wx.Dialog):
  def __init__(self, *args, **kwds):
    # begin wxGlade: CloneDialog.__init__
    kwds["style"] = kwds.get("style", 0) | wx.DEFAULT_DIALOG_STYLE | wx.RESIZE_BORDER | wx.STAY_ON_TOP
    wx.Dialog.__init__(self, *args, **kwds)
    self.SetTitle("Clone Dialog")

    top_vert_sizer = wx.BoxSizer(wx.VERTICAL)

    sizer_field_vert = wx.BoxSizer(wx.VERTICAL)
    top_vert_sizer.Add(sizer_field_vert, 0, wx.EXPAND, 0)

    self.gh_list = wx.ListCtrl(self, wx.ID_ANY, style=wx.LC_HRULES | wx.LC_REPORT | wx.LC_SINGLE_SEL | wx.LC_VRULES)
    self.gh_list.AppendColumn("Repo Name", format=wx.LIST_FORMAT_LEFT, width=181)
    sizer_field_vert.Add(self.gh_list, 1, wx.EXPAND, 0)

    sizer_alt_repo_entry = wx.BoxSizer(wx.HORIZONTAL)
    sizer_field_vert.Add(sizer_alt_repo_entry, 0, wx.ALIGN_RIGHT, 0)

    url_prompt = wx.StaticText(self, wx.ID_ANY, "or enter url:")
    sizer_alt_repo_entry.Add(url_prompt, 1, wx.EXPAND, 0)

    self.text_ctrl_url = wx.TextCtrl(self, wx.ID_ANY, "")
    sizer_alt_repo_entry.Add(self.text_ctrl_url, 9, wx.EXPAND, 0)

    sizer_repo_select_copy = wx.BoxSizer(wx.HORIZONTAL)
    sizer_field_vert.Add(sizer_repo_select_copy, 0, wx.EXPAND | wx.FIXED_MINSIZE, 0)

    self.btn_select_dest = wx.Button(self, wx.ID_ANY, "const.REPOS_DIRECTORY")
    self.btn_select_dest.SetMinSize(wx.Size(75, 23))
    self.btn_select_dest.SetLabel(const.REPOS_DIRECTORY)
    sizer_repo_select_copy.Add(self.btn_select_dest, 1, wx.EXPAND, 0)

    sizer_dlg_buttons = wx.StdDialogButtonSizer()
    top_vert_sizer.Add(sizer_dlg_buttons, 0, wx.ALIGN_RIGHT, 0)

    self.btn_clone = wx.Button(self, wx.ID_ANY, "Clone!")
    self.btn_clone.SetDefault()
    sizer_dlg_buttons.Add(self.btn_clone, 0, 0, 0)

    self.btn_cancel = wx.Button(self, wx.ID_CANCEL, "")
    sizer_dlg_buttons.AddButton(self.btn_cancel)

    sizer_dlg_buttons.Realize()

    self.SetSizer(top_vert_sizer)
    top_vert_sizer.Fit(self)
    top_vert_sizer.SetSizeHints(self)

    self.SetAffirmativeId(self.btn_clone.GetId())
    self.SetEscapeId(self.btn_cancel.GetId())

    self.Layout()

    self.btn_select_dest.Bind(wx.EVT_BUTTON, self.select_repos_directory)
    # end wxGlade

  def select_repos_directory(self, event: wx.CommandEvent):  # wxGlade: CloneDialog.<event_handler>
    with wx.DirDialog(self, "Choose a directory") as dlg:
      if dlg.ShowModal() == wx.ID_OK:
        # Get the selected directory path
        selected_dir = dlg.GetPath()
        self.btn_select_dest.SetLabel(selected_dir)
    event.Skip()
# end of class CloneDialog
