# -*- coding: UTF-8 -*-
#
# generated by wxGlade 1.1.1 on Fri Sep 12 18:05:19 2025
#
import sys

import wx
# begin wxGlade: dependencies
from wxasync import AsyncBind

from actions import repo_search
from console_output import ConsoleOutput


# end wxGlade

# begin wxGlade: extracode
# end wxGlade


class MyFrame(wx.Frame):
    def __init__(self, *args, **kwds):
        # begin wxGlade: MyFrame.__init__
        kwds["style"] = kwds.get("style", 0) | wx.DEFAULT_FRAME_STYLE
        wx.Frame.__init__(self, *args, **kwds)
        self.SetSize(wx.Size(1057, 1039))
        self.SetTitle("frame")

        self.notebook_1 = wx.Notebook(self, wx.ID_ANY, style=wx.NB_BOTTOM)

        self.split_pane = wx.SplitterWindow(self.notebook_1, wx.ID_ANY)
        self.split_pane.SetMinimumPaneSize(400)
        self.notebook_1.AddPage(self.split_pane, "Actions")

        self.all_repos = wx.Panel(self.split_pane, wx.ID_ANY)

        sizer_1 = wx.BoxSizer(wx.VERTICAL)

        sizer_2 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_1.Add(sizer_2, 90, 0, 0)

        self.list_all_repos = wx.ListCtrl(self.all_repos, wx.ID_ANY, style=wx.LC_HRULES | wx.LC_REPORT | wx.LC_VRULES)
        self.list_all_repos.SetToolTip("These are all the repos you have found on your system.")
        self.list_all_repos.AppendColumn("All Repos", format=wx.LIST_FORMAT_LEFT,
                                         width=self.list_all_repos.GetSize().GetWidth())
        sizer_2.Add(self.list_all_repos, 90, wx.EXPAND, 0)

        btns_repo_selection = wx.BoxSizer(wx.VERTICAL)
        sizer_2.Add(btns_repo_selection, 1, wx.ALIGN_CENTER_VERTICAL, 0)

        self.btn_rm = wx.Button(self.all_repos, wx.ID_ANY, "<", style=wx.BU_EXACTFIT)
        btns_repo_selection.Add(self.btn_rm, 0, 0, 0)

        self.btn_add = wx.Button(self.all_repos, wx.ID_ANY, ">", style=wx.BU_EXACTFIT)
        btns_repo_selection.Add(self.btn_add, 0, 0, 0)

        self.btn_clear = wx.Button(self.all_repos, wx.ID_ANY, "<=", style=wx.BU_EXACTFIT)
        btns_repo_selection.Add(self.btn_clear, 0, 0, 0)

        self.btn_add_all = wx.Button(self.all_repos, wx.ID_ANY, "=>", style=wx.BU_EXACTFIT)
        btns_repo_selection.Add(self.btn_add_all, 0, 0, 0)

        grid_sizer_2 = wx.FlexGridSizer(2, 2, 0, 0)
        sizer_1.Add(grid_sizer_2, 10, wx.EXPAND, 0)

        self.btn_scan_for_repos = wx.Button(self.all_repos, wx.ID_ANY, "Scan for repos")
        grid_sizer_2.Add(self.btn_scan_for_repos, 0, 0, 0)

        self.btn_rmv_invalid_repos = wx.Button(self.all_repos, wx.ID_ANY, "Remove invalid repos")
        grid_sizer_2.Add(self.btn_rmv_invalid_repos, 0, 0, 0)

        self.btn_add_repo = wx.Button(self.all_repos, wx.ID_ANY, "Add new repo")
        grid_sizer_2.Add(self.btn_add_repo, 0, 0, 0)

        self.btn_rm_repo = wx.Button(self.all_repos, wx.ID_ANY, "Remove repo(s)")
        grid_sizer_2.Add(self.btn_rm_repo, 0, 0, 0)

        self.working_repos = wx.Panel(self.split_pane, wx.ID_ANY)

        sizer_3 = wx.BoxSizer(wx.VERTICAL)

        self.list_working_repos = wx.ListCtrl(self.working_repos, wx.ID_ANY,
                                              style=wx.LC_HRULES | wx.LC_REPORT | wx.LC_VRULES)
        self.list_working_repos.SetToolTip("These are the repos you are currently working with.")
        self.list_working_repos.AppendColumn("Working Repos", format=wx.LIST_FORMAT_LEFT,
                                             width=self.list_working_repos.GetSize().GetWidth())
        sizer_3.Add(self.list_working_repos, 90, wx.EXPAND, 0)

        grid_sizer_3 = wx.FlexGridSizer(3, 3, 0, 0)
        sizer_3.Add(grid_sizer_3, 10, wx.EXPAND, 0)

        self.checkbox_1 = wx.CheckBox(self.working_repos, wx.ID_ANY, "Force Mode")
        grid_sizer_3.Add(self.checkbox_1, 0, 0, 0)

        self.panel_1 = wx.Panel(self.working_repos, wx.ID_ANY)
        grid_sizer_3.Add(self.panel_1, 1, wx.EXPAND, 0)

        self.panel_2 = wx.Panel(self.working_repos, wx.ID_ANY)
        grid_sizer_3.Add(self.panel_2, 1, wx.EXPAND, 0)

        self.btn_reset = wx.Button(self.working_repos, wx.ID_ANY, "Reset")
        grid_sizer_3.Add(self.btn_reset, 0, 0, 0)

        self.btn_pull = wx.Button(self.working_repos, wx.ID_ANY, "Pull")
        grid_sizer_3.Add(self.btn_pull, 0, 0, 0)

        self.btn_push = wx.Button(self.working_repos, wx.ID_ANY, "Push")
        grid_sizer_3.Add(self.btn_push, 0, 0, 0)

        self.btn_reset_all = wx.Button(self.working_repos, wx.ID_ANY, "Reset All")
        grid_sizer_3.Add(self.btn_reset_all, 0, 0, 0)

        self.btn_pull_all = wx.Button(self.working_repos, wx.ID_ANY, "Pull All")
        grid_sizer_3.Add(self.btn_pull_all, 0, 0, 0)

        self.btn_push_all = wx.Button(self.working_repos, wx.ID_ANY, "Push All")
        grid_sizer_3.Add(self.btn_push_all, 0, 0, 0)

        self.log_window = wx.TextCtrl(self.notebook_1, wx.ID_ANY, "", style=wx.TE_READONLY | wx.TE_MULTILINE)
        self.notebook_1.AddPage(self.log_window, "Log")

        sys.stdout = ConsoleOutput(self.log_window)
        sys.stderr = ConsoleOutput(self.log_window)

        grid_sizer_3.AddGrowableCol(0)
        grid_sizer_3.AddGrowableCol(1)
        grid_sizer_3.AddGrowableCol(2)

        self.working_repos.SetSizer(sizer_3)

        grid_sizer_2.AddGrowableCol(0)
        grid_sizer_2.AddGrowableCol(1)

        self.all_repos.SetSizer(sizer_1)

        self.split_pane.SplitVertically(self.all_repos, self.working_repos)

        self.Layout()

        # Bind the repo management buttons
        self.btn_rm.Bind(wx.EVT_BUTTON, self.remove_repo_from_working_set)
        self.btn_add.Bind(wx.EVT_BUTTON, self.add_repo_to_working_set)
        self.btn_clear.Bind(wx.EVT_BUTTON, self.clear_working_set)
        self.btn_add_all.Bind(wx.EVT_BUTTON, self.add_all_repos_to_working_set)

        # Bind events for resizing the window
        self.list_all_repos.Bind(wx.EVT_SIZE, self.on_resize)
        self.list_working_repos.Bind(wx.EVT_SIZE, self.on_resize)
        # self.btn_scan_for_repos.Bind(wx.EVT_BUTTON, self.scan_for_repos)
        AsyncBind(wx.EVT_BUTTON, self.scan_for_repos, self.btn_scan_for_repos)
        self.btn_rmv_invalid_repos.Bind(wx.EVT_BUTTON, self.remove_invalid_repos_from_all)
        self.btn_add_repo.Bind(wx.EVT_BUTTON, self.add_new_repo_to_all)
        self.btn_rm_repo.Bind(wx.EVT_BUTTON, self.remove_repo_from_all)
        self.checkbox_1.Bind(wx.EVT_CHECKBOX, self.force_mode_changed)
        self.btn_reset.Bind(wx.EVT_BUTTON, self.reset_selected_repos)
        self.btn_pull.Bind(wx.EVT_BUTTON, self.pull_selected_repos)
        self.btn_push.Bind(wx.EVT_BUTTON, self.push_selected_repos)
        self.btn_reset_all.Bind(wx.EVT_BUTTON, self.reset_all_working_repos)
        self.btn_pull_all.Bind(wx.EVT_BUTTON, self.pull_all_repos)
        self.btn_push_all.Bind(wx.EVT_BUTTON, self.push_all_repos)
        # end wxGlade

    def show_log(self):
        self.notebook_1.SetSelection(1)

    def show_actions(self):
        self.notebook_1.SetSelection(0)

    def remove_repo_from_working_set(self, event: wx.CommandEvent):
        src = self.list_working_repos
        target = self.list_all_repos

        item = src.GetFirstSelected(-1)

        while src.GetSelectedItemCount() > 0:
            # if item == wx.NOT_FOUND: return

            item_name = src.GetItemText(item)
            # print(item_name)

            add_item_to_list(target, item_name)
            src.DeleteItem(item)

            item = src.GetNextSelected(item)

    def add_repo_to_working_set(self, event: wx.CommandEvent):
        src = self.list_all_repos
        target = self.list_working_repos

        item = src.GetFirstSelected(-1)

        while src.GetSelectedItemCount() > 0:
            # if item == wx.NOT_FOUND: return

            item_name = src.GetItemText(item)
            # print(item_name)

            add_item_to_list(target, item_name)
            item = src.GetNextSelected(item)

    def clear_working_set(self, event: wx.CommandEvent):
        src = self.list_working_repos
        target = self.list_all_repos

        item = src.GetNextItem(-1)

        while src.GetItemCount() > 0:
            if item != wx.NOT_FOUND:
                item_name = src.GetItemText(item)
                # print(item_name)

                add_item_to_list(target, item_name)
                src.DeleteItem(item)

            item = src.GetNextItem(item)

        # src.DeleteAllItems()

    def add_all_repos_to_working_set(self, event: wx.CommandEvent):
        src = self.list_all_repos
        target = self.list_working_repos

        item = src.GetNextItem(-1)

        while True:
            # if src.GetItemCount() == target.GetItemCount(): return
            if item == wx.NOT_FOUND: return

            item_name = src.GetItemText(item)
            # print(item_name)

            add_item_to_list(target, item_name)
            # src.Select(item, 0 )

            item = src.GetNextItem(item)

    async def scan_for_repos(self, event: wx.CommandEvent):  # wxGlade: MyFrame.<event_handler>
        self.show_log()

        async for value in repo_search():
            add_item_to_list(self.list_all_repos, value)
            print(value)

        self.show_actions()
        event.Skip()

    def remove_invalid_repos_from_all(self, event: wx.CommandEvent):  # wxGlade: MyFrame.<event_handler>
        print("Event handler 'remove_invalid_repos_from_all' not implemented!")
        event.Skip()

    def add_new_repo_to_all(self, event: wx.CommandEvent):  # wxGlade: MyFrame.<event_handler>
        print("Event handler 'add_new_repo_to_all' not implemented!")
        event.Skip()

    def remove_repo_from_all(self, event: wx.CommandEvent):  # wxGlade: MyFrame.<event_handler>
        src = self.list_all_repos

        item = src.GetFirstSelected(-1)

        while src.GetSelectedItemCount() > 0:
            # if item == wx.NOT_FOUND: return

            # item_name = src.GetItemText(item)
            # print(item_name)

            src.DeleteItem(item)

            item = src.GetNextSelected(item)

    def force_mode_changed(self, event: wx.CommandEvent):  # wxGlade: MyFrame.<event_handler>
        print("Event handler 'force_mode_changed' not implemented!")
        event.Skip()

    def reset_selected_repos(self, event: wx.CommandEvent):  # wxGlade: MyFrame.<event_handler>
        print("Event handler 'reset_selected_repos' not implemented!")
        event.Skip()

    def pull_selected_repos(self, event: wx.CommandEvent):  # wxGlade: MyFrame.<event_handler>
        print("Event handler 'pull_selected_repos' not implemented!")
        event.Skip()

    def push_selected_repos(self, event: wx.CommandEvent):  # wxGlade: MyFrame.<event_handler>
        print("Event handler 'push_selected_repos' not implemented!")
        event.Skip()

    def reset_all_working_repos(self, event: wx.CommandEvent):  # wxGlade: MyFrame.<event_handler>
        print("Event handler 'reset_all_working_repos' not implemented!")
        event.Skip()

    def pull_all_repos(self, event: wx.CommandEvent):  # wxGlade: MyFrame.<event_handler>
        print("Event handler 'pull_all_repos' not implemented!")
        event.Skip()

    def push_all_repos(self, event: wx.CommandEvent):  # wxGlade: MyFrame.<event_handler>
        print("Event handler 'push_all_repos' not implemented!")
        event.Skip()

    def on_resize(self, event: wx.SizeEvent):  # wxGlade: MyFrame.<event_handler>
        # Get current width of the ListCtrl
        all_width = self.list_all_repos.GetSize().GetWidth()
        working_width = self.list_working_repos.GetSize().GetWidth()
        # Set column width to full width (minus borders / scrollbar space if needed
        self.list_all_repos.SetColumnWidth(0, all_width)
        self.list_working_repos.SetColumnWidth(1, working_width)
        event.Skip()
# end of class MyFrame


def add_item_to_list(list_ctrl: wx.ListCtrl, repo_name: str):
    index = list_ctrl.FindItem(-1, repo_name)
    if index == wx.NOT_FOUND:
        list_ctrl.InsertItem(list_ctrl.GetItemCount(), repo_name)


def ctrl_to_str(list_ctrl: wx.ListCtrl) -> list[str]:
    result = []

    item = list_ctrl.GetNextItem(-1)
    while True:
        if item == wx.NOT_FOUND: return result

        result.append(list_ctrl.GetItemText(item))

        item = list_ctrl.GetNextItem(item)


def str_to_ctrl(item_list: list[str], list_ctrl: wx.ListCtrl):
    list_ctrl.DeleteAllItems()
    for item in item_list:
        add_item_to_list(list_ctrl, item)
