# -*- coding: UTF-8 -*-
#
# generated by wxGlade 1.1.1 on Fri Sep 12 18:05:19 2025
#
import sys

import wx
import wx.adv

import list_management
import menu_actions
from DragSelectList import DragSelectList
# begin wxGlade: dependencies
from console_output import ConsoleOutput


# end wxGlade

# begin wxGlade: extracode
# end wxGlade


class MyFrame(wx.Frame):
    task_started = False
    exit_task_running = False

    def __init__(self, *args, **kwargs):
        # begin wxGlade: MyFrame.__init__
        kwargs["style"] = kwargs.get("style", 0) | wx.DEFAULT_FRAME_STYLE
        wx.Frame.__init__(self, *args, **kwargs)
        self.SetSize(wx.Size(1057, 1039))
        self.SetTitle("frame")

        self.notebook_1 = wx.Notebook(self, wx.ID_ANY, style=wx.NB_BOTTOM)

        self.split_pane = wx.SplitterWindow(self.notebook_1, wx.ID_ANY)
        self.split_pane.SetMinimumPaneSize(400)
        self.notebook_1.AddPage(self.split_pane, "Actions")

        self.all_repos = wx.Panel(self.split_pane, wx.ID_ANY)

        sizer_1 = wx.BoxSizer(wx.VERTICAL)

        sizer_2 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_1.Add(sizer_2, 90, 0, 0)

        self.list_all_repos = DragSelectList(self.all_repos)
        self.list_all_repos.SetToolTip("These are all the repos you have found on your system.")
        self.list_all_repos.AppendColumn("All Repos", format=wx.LIST_FORMAT_LEFT,
                                         width=self.list_all_repos.GetSize().GetWidth())
        sizer_2.Add(self.list_all_repos, 90, wx.EXPAND, 0)

        btns_repo_selection = wx.BoxSizer(wx.VERTICAL)
        sizer_2.Add(btns_repo_selection, 1, wx.ALIGN_CENTER_VERTICAL, 0)

        self.btn_rm = wx.Button(self.all_repos, wx.ID_ANY, "<", style=wx.BU_EXACTFIT)
        btns_repo_selection.Add(self.btn_rm, 0, 0, 0)

        self.btn_add = wx.Button(self.all_repos, wx.ID_ANY, ">", style=wx.BU_EXACTFIT)
        btns_repo_selection.Add(self.btn_add, 0, 0, 0)

        self.btn_clear = wx.Button(self.all_repos, wx.ID_ANY, "<=", style=wx.BU_EXACTFIT)
        btns_repo_selection.Add(self.btn_clear, 0, 0, 0)

        self.btn_add_all = wx.Button(self.all_repos, wx.ID_ANY, "=>", style=wx.BU_EXACTFIT)
        btns_repo_selection.Add(self.btn_add_all, 0, 0, 0)

        grid_sizer_2 = wx.FlexGridSizer(2, 2, 0, 0)
        sizer_1.Add(grid_sizer_2, 10, wx.EXPAND, 0)

        self.btn_scan_for_repos = wx.Button(self.all_repos, wx.ID_ANY, "Scan for repos")
        grid_sizer_2.Add(self.btn_scan_for_repos, 0, 0, 0)

        self.btn_rmv_invalid_repos = wx.Button(self.all_repos, wx.ID_ANY, "Remove invalid repos")
        grid_sizer_2.Add(self.btn_rmv_invalid_repos, 0, 0, 0)

        self.btn_add_repo = wx.Button(self.all_repos, wx.ID_ANY, "Add new repo")
        grid_sizer_2.Add(self.btn_add_repo, 0, 0, 0)

        self.btn_rm_repo = wx.Button(self.all_repos, wx.ID_ANY, "Remove repo(s)")
        self.btn_rm_repo.Enable(False)
        grid_sizer_2.Add(self.btn_rm_repo, 0, 0, 0)

        self.working_repos = wx.Panel(self.split_pane, wx.ID_ANY)

        sizer_3 = wx.BoxSizer(wx.VERTICAL)

        self.list_working_repos = DragSelectList(self.working_repos)
        self.list_working_repos.SetToolTip("These are the repos you are currently working with.")
        self.list_working_repos.AppendColumn("Working Repos", format=wx.LIST_FORMAT_LEFT,
                                             width=self.list_working_repos.GetSize().GetWidth())
        sizer_3.Add(self.list_working_repos, 90, wx.EXPAND, 0)

        grid_sizer_3 = wx.FlexGridSizer(3, 3, 0, 0)
        sizer_3.Add(grid_sizer_3, 10, wx.EXPAND, 0)

        self.force_mode = wx.CheckBox(self.working_repos, wx.ID_ANY, "Force Mode")
        grid_sizer_3.Add(self.force_mode, 0, 0, 0)

        self.panel_1 = wx.Panel(self.working_repos, wx.ID_ANY)
        grid_sizer_3.Add(self.panel_1, 1, wx.EXPAND, 0)

        self.panel_2 = wx.Panel(self.working_repos, wx.ID_ANY)
        grid_sizer_3.Add(self.panel_2, 1, wx.EXPAND, 0)

        self.btn_reset = wx.Button(self.working_repos, wx.ID_ANY, "Reset")
        self.btn_reset.Enable(False)
        grid_sizer_3.Add(self.btn_reset, 0, 0, 0)

        self.btn_pull = wx.Button(self.working_repos, wx.ID_ANY, "Pull")
        self.btn_pull.Enable(False)
        grid_sizer_3.Add(self.btn_pull, 0, 0, 0)

        self.btn_push = wx.Button(self.working_repos, wx.ID_ANY, "Push")
        self.btn_push.Enable(False)
        grid_sizer_3.Add(self.btn_push, 0, 0, 0)

        self.btn_reset_all = wx.Button(self.working_repos, wx.ID_ANY, "Reset All")
        self.btn_reset_all.Enable(False)
        grid_sizer_3.Add(self.btn_reset_all, 0, 0, 0)

        self.btn_pull_all = wx.Button(self.working_repos, wx.ID_ANY, "Pull All")
        self.btn_pull_all.Enable(False)
        grid_sizer_3.Add(self.btn_pull_all, 0, 0, 0)

        self.btn_push_all = wx.Button(self.working_repos, wx.ID_ANY, "Push All")
        self.btn_push_all.Enable(False)
        grid_sizer_3.Add(self.btn_push_all, 0, 0, 0)

        self.log_window = wx.TextCtrl(self.notebook_1, wx.ID_ANY, "", style=wx.TE_READONLY | wx.TE_MULTILINE)
        self.notebook_1.AddPage(self.log_window, "Log")

        grid_sizer_3.AddGrowableCol(0)
        grid_sizer_3.AddGrowableCol(1)
        grid_sizer_3.AddGrowableCol(2)

        self.working_repos.SetSizer(sizer_3)

        grid_sizer_2.AddGrowableCol(0)
        grid_sizer_2.AddGrowableCol(1)

        self.all_repos.SetSizer(sizer_1)

        self.split_pane.SplitVertically(self.all_repos, self.working_repos)

        self.Layout()

        # Bind the repo management buttons
        self.btn_rm.Bind(wx.EVT_BUTTON, self.remove_repo_from_working_set)
        self.btn_add.Bind(wx.EVT_BUTTON, self.add_repo_to_working_set)
        self.btn_clear.Bind(wx.EVT_BUTTON, self.clear_working_set)
        self.btn_add_all.Bind(wx.EVT_BUTTON, self.add_all_repos_to_working_set)

        # Bind events for resizing the window
        self.list_all_repos.Bind(wx.EVT_SIZE, self.on_resize)
        self.list_working_repos.Bind(wx.EVT_SIZE, self.on_resize)
        self.list_working_repos.Bind(wx.EVT_LIST_ITEM_SELECTED, self.on_selection_changed)
        self.list_working_repos.Bind(wx.EVT_LIST_ITEM_DESELECTED, self.on_selection_changed)
        # self.btn_scan_for_repos.Bind(wx.EVT_BUTTON, self.scan_for_repos)
        # AsyncBind(wx.EVT_BUTTON, list_management.scan_for_repos, self.btn_scan_for_repos)
        self.btn_scan_for_repos.Bind(wx.EVT_BUTTON, lambda _: list_management.scan_task(self))
        self.btn_rmv_invalid_repos.Bind(wx.EVT_BUTTON, self.remove_invalid_repos_from_all)
        self.btn_add_repo.Bind(wx.EVT_BUTTON, self.add_new_repo_to_all)
        self.btn_rm_repo.Bind(wx.EVT_BUTTON, self.remove_repo_from_all)
        self.force_mode.Bind(wx.EVT_CHECKBOX, self.force_toggled)
        self.btn_reset.Bind(wx.EVT_BUTTON, self.reset_selected_repos)
        self.btn_pull.Bind(wx.EVT_BUTTON, self.pull_selected_repos)
        self.btn_push.Bind(wx.EVT_BUTTON, self.push_selected_repos)
        self.btn_reset_all.Bind(wx.EVT_BUTTON, self.reset_all_working_repos)
        self.btn_pull_all.Bind(wx.EVT_BUTTON, self.pull_all_repos)
        self.btn_push_all.Bind(wx.EVT_BUTTON, self.push_all_repos)
        # end wxGlade
        self.CreateStatusBar()
        self.SetStatusText("Ready")

        self.create_menu()
        # asyncio.run(self.load(None))
        self.Bind(wx.EVT_IDLE, self.on_idle_once)
        self.Bind(wx.EVT_CLOSE, self.on_exit)

        # Lastly forward the output to the log window.
        sys.stdout = ConsoleOutput(self.log_window)
        sys.stderr = ConsoleOutput(self.log_window)

    def on_selection_changed(self, event: wx.Event):
        self.btn_push.Enable(self.list_working_repos.GetSelectedItemCount() > 0)
        self.btn_pull.Enable(self.list_working_repos.GetSelectedItemCount() > 0)
        self.btn_rm_repo.Enable(self.list_working_repos.GetSelectedItemCount() > 0)
        self.btn_reset.Enable(self.list_working_repos.GetSelectedItemCount() > 0)
        self.btn_pull.Enable(self.list_working_repos.GetSelectedItemCount() > 0)
        self.btn_push.Enable(self.list_working_repos.GetSelectedItemCount() > 0)
        self.btn_reset_all.Enable(self.list_working_repos.GetItemCount() > 0)
        self.btn_pull_all.Enable(self.list_working_repos.GetItemCount() > 0)
        self.btn_push_all.Enable(self.list_working_repos.GetItemCount() > 0)
        event.Skip()

    def on_idle_once(self, event: wx.IdleEvent) -> None:
        if not self.task_started:
            self.task_started = True
            menu_actions.load_task(self)
        event.Skip()

    def on_exit(self, event: wx.CloseEvent) -> None:
        """Runs async task on exit before actually closing"""
        if not self.exit_task_running:
            self.exit_task_running = True
            self.SetStatusText("Saving before exiting")

            # Schedule async task
            menu_actions.final_save_task(self)

            # Prevent immediate close
            event.Veto()
        else:
            event.Skip()

    def create_menu(self):
        menu_bar = wx.MenuBar()
        file_menu = wx.Menu()

        load_item = file_menu.Append(wx.ID_ANY, "&Load\tCtrl-L", "Load the previously saved list of repositories")
        save_item = file_menu.Append(wx.ID_SAVE, "&Save\tCtrl-S", "Save the current list of repositories")

        menu_bar.Append(file_menu, "&File")

        self.SetMenuBar(menu_bar)

        self.Bind(wx.EVT_MENU, lambda _: menu_actions.load_task(self), load_item)
        # AsyncBind(wx.EVT_MENU, menu_actions.load_task, self, load_item)
        self.Bind(wx.EVT_MENU, lambda _: menu_actions.save_task(self), save_item)
        # AsyncBind(wx.EVT_MENU, menu_actions.save_task, self, save_item)

    def show_log(self):
        self.notebook_1.SetSelection(1)

    def show_actions(self):
        self.notebook_1.SetSelection(0)

    def remove_repo_from_working_set(self, _event: wx.CommandEvent):
        list_management.move_selection(self.list_working_repos, self.list_all_repos)
        self.on_selection_changed(_event)

    def add_repo_to_working_set(self, _event: wx.CommandEvent):
        list_management.copy_selection(self.list_all_repos, self.list_working_repos)
        self.on_selection_changed(_event)

    def clear_working_set(self, _event: wx.CommandEvent):
        list_management.move_repos(self.list_working_repos, self.list_all_repos)
        self.on_selection_changed(_event)
        # src.DeleteAllItems()

    def add_all_repos_to_working_set(self, _event: wx.CommandEvent):
        list_management.copy_repos(self.list_all_repos, self.list_working_repos)
        self.on_selection_changed(_event)

    def remove_invalid_repos_from_all(self, event: wx.CommandEvent):  # wxGlade: MyFrame.<event_handler>
        print("Event handler 'remove_invalid_repos_from_all' not implemented!")
        event.Skip()

    def add_new_repo_to_all(self, event: wx.CommandEvent):  # wxGlade: MyFrame.<event_handler>
        print("Event handler 'add_new_repo_to_all' not implemented!")
        event.Skip()

    def remove_repo_from_all(self, _event: wx.CommandEvent):  # wxGlade: MyFrame.<event_handler>
        list_management.remove_selection(self.list_all_repos)

    def force_toggled(self, event: wx.CommandEvent):  # wxGlade: MyFrame.<event_handler>
        print("Event handler 'force_mode_changed' not implemented!")
        event.Skip()

    def reset_selected_repos(self, event: wx.CommandEvent):  # wxGlade: MyFrame.<event_handler>
        print("Event handler 'reset_selected_repos' not implemented!")
        event.Skip()

    def pull_selected_repos(self, event: wx.CommandEvent):  # wxGlade: MyFrame.<event_handler>
        print("Event handler 'pull_selected_repos' not implemented!")
        event.Skip()

    def push_selected_repos(self, event: wx.CommandEvent):  # wxGlade: MyFrame.<event_handler>
        print("Event handler 'push_selected_repos' not implemented!")
        event.Skip()

    def reset_all_working_repos(self, event: wx.CommandEvent):  # wxGlade: MyFrame.<event_handler>
        print("Event handler 'reset_all_working_repos' not implemented!")
        event.Skip()

    def pull_all_repos(self, event: wx.CommandEvent):  # wxGlade: MyFrame.<event_handler>
        print("Event handler 'pull_all_repos' not implemented!")
        event.Skip()

    def push_all_repos(self, event: wx.CommandEvent):  # wxGlade: MyFrame.<event_handler>
        print("Event handler 'push_all_repos' not implemented!")
        event.Skip()

    def on_resize(self, event: wx.SizeEvent):  # wxGlade: MyFrame.<event_handler>
        # Get current width of the ListCtrl
        all_width = self.list_all_repos.GetSize().GetWidth()
        working_width = self.list_working_repos.GetSize().GetWidth()
        # Set column width to full width (minus borders / scrollbar space if needed
        self.list_all_repos.SetColumnWidth(0, all_width)
        self.list_working_repos.SetColumnWidth(1, working_width)
        event.Skip()
# end of class MyFrame
