#!/usr/bin/env python3
# -*- coding: UTF-8 -*-
#
# generated by wxGlade 1.1.1 on Thu Sep 11 19:23:14 2025
#

import wx

# begin wxGlade: dependencies
# end wxGlade

# begin wxGlade: extracode
# end wxGlade


class MyFrame(wx.Frame):
    def __init__(self, *args, **kwds):
        # begin wxGlade: MyFrame.__init__
        kwds["style"] = kwds.get("style", 0) | wx.DEFAULT_FRAME_STYLE
        wx.Frame.__init__(self, *args, **kwds)
        self.SetSize((974, 1039))
        self.SetTitle("frame")

        self.notebook_1 = wx.Notebook(self, wx.ID_ANY, style=wx.NB_BOTTOM)

        self.split_pane = wx.SplitterWindow(self.notebook_1, wx.ID_ANY)
        self.split_pane.SetMinimumPaneSize(400)
        self.notebook_1.AddPage(self.split_pane, "Actions")

        self.all_repos = wx.Panel(self.split_pane, wx.ID_ANY)

        sizer_1 = wx.BoxSizer(wx.VERTICAL)

        sizer_2 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_1.Add(sizer_2, 1, 0, 0)

        self.list_all_repos = wx.ListCtrl(self.all_repos, wx.ID_ANY, style=wx.LC_HRULES | wx.LC_REPORT | wx.LC_VRULES)
        self.list_all_repos.AppendColumn("A", format=wx.LIST_FORMAT_LEFT, width=138)
        self.list_all_repos.AppendColumn("B", format=wx.LIST_FORMAT_LEFT, width=-1)
        self.list_all_repos.AppendColumn("C", format=wx.LIST_FORMAT_LEFT, width=-1)
        sizer_2.Add(self.list_all_repos, 90, wx.EXPAND, 0)

        btns_repo_selection = wx.BoxSizer(wx.VERTICAL)
        sizer_2.Add(btns_repo_selection, 1, wx.ALIGN_CENTER_VERTICAL, 0)

        self.btn_rm = wx.Button(self.all_repos, wx.ID_ANY, "<", style=wx.BU_EXACTFIT)
        btns_repo_selection.Add(self.btn_rm, 0, 0, 0)

        self.btn_add = wx.Button(self.all_repos, wx.ID_ANY, ">", style=wx.BU_EXACTFIT)
        btns_repo_selection.Add(self.btn_add, 0, 0, 0)

        self.btn_clear = wx.Button(self.all_repos, wx.ID_ANY, "<=", style=wx.BU_EXACTFIT)
        btns_repo_selection.Add(self.btn_clear, 0, 0, 0)

        self.btn_add_all = wx.Button(self.all_repos, wx.ID_ANY, "=>", style=wx.BU_EXACTFIT)
        btns_repo_selection.Add(self.btn_add_all, 0, 0, 0)

        grid_sizer_2 = wx.FlexGridSizer(2, 2, 0, 0)
        sizer_1.Add(grid_sizer_2, 1, wx.EXPAND, 0)

        self.button_11 = wx.Button(self.all_repos, wx.ID_ANY, "Scan for repos")
        grid_sizer_2.Add(self.button_11, 0, 0, 0)

        self.button_12 = wx.Button(self.all_repos, wx.ID_ANY, "Remove invalid repos")
        grid_sizer_2.Add(self.button_12, 0, 0, 0)

        self.button_13 = wx.Button(self.all_repos, wx.ID_ANY, "Add new repo")
        grid_sizer_2.Add(self.button_13, 0, 0, 0)

        self.button_14 = wx.Button(self.all_repos, wx.ID_ANY, "Remove repo")
        grid_sizer_2.Add(self.button_14, 0, 0, 0)

        self.working_repos = wx.Panel(self.split_pane, wx.ID_ANY)

        sizer_3 = wx.BoxSizer(wx.VERTICAL)

        self.list_working_repos = wx.ListCtrl(self.working_repos, wx.ID_ANY, style=wx.LC_HRULES | wx.LC_REPORT | wx.LC_VRULES)
        self.list_working_repos.AppendColumn("A", format=wx.LIST_FORMAT_LEFT, width=-1)
        self.list_working_repos.AppendColumn("B", format=wx.LIST_FORMAT_LEFT, width=-1)
        self.list_working_repos.AppendColumn("C", format=wx.LIST_FORMAT_LEFT, width=-1)
        sizer_3.Add(self.list_working_repos, 1, wx.EXPAND, 0)

        grid_sizer_3 = wx.FlexGridSizer(3, 3, 0, 0)
        sizer_3.Add(grid_sizer_3, 1, wx.EXPAND, 0)

        self.checkbox_1 = wx.CheckBox(self.working_repos, wx.ID_ANY, "Force Mode")
        grid_sizer_3.Add(self.checkbox_1, 0, 0, 0)

        self.button_21 = wx.Button(self.working_repos, wx.ID_ANY, "Push")
        grid_sizer_3.Add(self.button_21, 0, 0, 0)

        self.button_22 = wx.Button(self.working_repos, wx.ID_ANY, "Pull")
        grid_sizer_3.Add(self.button_22, 0, 0, 0)

        self.button_23 = wx.Button(self.working_repos, wx.ID_ANY, "Push All")
        grid_sizer_3.Add(self.button_23, 0, 0, 0)

        self.button_24 = wx.Button(self.working_repos, wx.ID_ANY, "Pull All")
        grid_sizer_3.Add(self.button_24, 0, 0, 0)

        self.button_25 = wx.Button(self.working_repos, wx.ID_ANY, "button_25")
        grid_sizer_3.Add(self.button_25, 0, 0, 0)

        self.button_26 = wx.Button(self.working_repos, wx.ID_ANY, "button_26")
        grid_sizer_3.Add(self.button_26, 0, 0, 0)

        self.button_27 = wx.Button(self.working_repos, wx.ID_ANY, "button_27")
        grid_sizer_3.Add(self.button_27, 0, 0, 0)

        self.button_28 = wx.Button(self.working_repos, wx.ID_ANY, "button_28")
        grid_sizer_3.Add(self.button_28, 0, 0, 0)

        self.log_window = wx.TextCtrl(self.notebook_1, wx.ID_ANY, "", style=wx.TE_READONLY)
        self.notebook_1.AddPage(self.log_window, "Log")

        grid_sizer_3.AddGrowableCol(0)
        grid_sizer_3.AddGrowableCol(1)
        grid_sizer_3.AddGrowableCol(2)

        self.working_repos.SetSizer(sizer_3)

        grid_sizer_2.AddGrowableCol(0)
        grid_sizer_2.AddGrowableCol(1)

        self.all_repos.SetSizer(sizer_1)

        self.split_pane.SplitVertically(self.all_repos, self.working_repos)

        self.Layout()
        # end wxGlade

# end of class MyFrame

class MyApp(wx.App):
    def OnInit(self):
        self.frame = MyFrame(None, wx.ID_ANY, "")
        self.SetTopWindow(self.frame)
        self.frame.Show()
        return True

# end of class MyApp

if __name__ == "__main__":
    app = MyApp(0)
    app.MainLoop()
